### ISSUE TITLE
在转换浮点型数字的时候似乎会报错

### ISSUE THREAD

**Issue by zenghaojim33** [sutar/JSON2Mantle#3]
好像只能转成NSInteger，如果JSON中出现了浮点数的时候不会转换成CGFloat。建议统一转换成NSNumber

**Comment by iflyingboots** [comment]
你用的是什么版本？在最新的版本 0.0.8 中 float 应该是没有问题的：
https://github.com/sutar/JSON2Mantle/blob/master/JSON2Mantle/cli.py#L191

关于 NSNumber，可能下个版本会弄吧。不过现在发现一个很重要的问题，Mantle 升级到 2.0 了。。。

**Comment by zenghaojim33** [comment]
可能是之前的版本吧，mantle2.0不能用了么？

**Comment by iflyingboots** [comment]
Mantle 2.0 有部分 API 改动与 1.x 不兼容。 

比如：

> Replace occurrences of +[NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:] with +[MTLJSONAdapter dictionaryTransformerWithModelClass:]

Ref: https://github.com/Mantle/Mantle/blob/2.0/CHANGELOG.md
